# Generated by Django 5.2.2 on 2025-07-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=150, null=True)),
                ('user_role', models.CharField(choices=[('Bills', 'Bills'), ('Client', 'Client'), ('Supplier', 'Supplier')], default='Bills', help_text='Select the Role', max_length=20, verbose_name='Role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
