# Generated by Django 5.2.2 on 2025-06-07 21:35

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Full name')),
                ('email', models.EmailField(blank=True, max_length=255, unique=True, verbose_name='Email address')),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Enter a valid international phone number (7-15 digits, optional leading '+').", regex='^\\+?\\d{7,15}$')], verbose_name='Phone number')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Additional information')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_contact_email_ci')],
            },
        ),
    ]
