# Generated by Django 5.2.2 on 2025-06-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lite_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinemeetingtasks',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Baja'), ('Pending', 'Alta'), ('Completed', 'Media')], default='Canceled', help_text='Select the status', max_length=20, verbose_name='Status'),
        ),
    ]
