# Generated by Django 5.2.2 on 2025-06-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lite_store', '0002_onlinemeetingtasks_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_situation', models.TextField(null=True)),
                ('context', models.JSONField(null=True)),
                ('needs', models.JSONField(null=True)),
                ('proposal', models.TextField(null=True)),
            ],
        ),
    ]
