# Generated by Django 5.2.2 on 2025-06-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lite_store', '0003_consultantresponses'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinemeetingtasks',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
