# Generated by Django 5.2.2 on 2025-06-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lite_store', '0004_onlinemeetingtasks_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinemeetingtasks',
            name='summary',
        ),
        migrations.AddField(
            model_name='onlinemeetingsanalyzed',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
