# Generated by Django 5.2.2 on 2025-06-25 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lite_store', '0005_remove_onlinemeetingtasks_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineReminderTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Pending', 'Pending')], default='Pending', help_text='Select the status', max_length=20, verbose_name='Status')),
                ('notification_date', models.DateField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('task_reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reminders', to='lite_store.onlinemeetingtasks')),
            ],
        ),
    ]
